#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_x = 1) in;

layout(set = 1, binding = 0) uniform sampler2D albedoMap;
layout(set = 1, binding = 1) uniform sampler2D positionMap;
layout(set = 1, binding = 2) uniform sampler2D normalMap;
layout(set = 1, binding = 3) uniform sampler2D depthMap;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage; 

vec3 lightPosition = vec3(0,3,0);

float random(vec3 p) 
{
    return fract(sin(dot(p, vec3(12.9898, 78.233, 45.164))) * 43758.5453123);
}


void main()
{
    uvec2 coord = gl_GlobalInvocationID.xy;
    uvec2 size = imageSize(outputImage);

    vec2 uv = vec2(coord) / vec2(size);

    if(coord.x > size.x || coord.y > size.y)
        return;

    vec3 albedo = texture(albedoMap, uv).rgb;
    vec3 position = texture(positionMap, uv).rgb;   
    vec3 normal = texture(normalMap, uv).rgb;
    float depth = texture(depthMap, uv).r;

    vec3 lightDirection = lightPosition - position;
    
    float dis = length(lightDirection);
    float inv = 1.0 / pow(dis, 2.0);

    lightDirection = normalize(lightDirection);

    float diffuse = max(dot(normal, lightDirection), 0.0);

    vec4 color = vec4(1,1,1,1);

    float ambient = 0.1;

    float intensity = 5;
    // color.a = 1.0;
    color.rgb *= (diffuse * intensity * inv) + ambient;

    float originDistance = distance(position, vec3(0));

    // if(depth > 0.9)
    //     color.rgb = albedo;

    imageStore(outputImage, ivec2(coord), color);
}